name: Release | VeriGate Develop

on:
  push:
    branches:
      - "main"

concurrency:
  group: verigate-dev
  cancel-in-progress: true

jobs:
  install:
    uses: ./.github/workflows/_install.yml
    with:
      java-version: "21"
    permissions:
      contents: read
      packages: read
    secrets: inherit

  integration-test:
    needs: [install]
    uses: ./.github/workflows/_test-integration-e2e.yml
    with:
      java-version: "21"
    permissions:
      contents: read
      packages: read
      checks: write
    secrets: inherit

  dev-deploy:
    needs: [install, integration-test]
    uses: ./.github/workflows/_release.verigate.yml
    with:
      java-version: "21"
      environment: dev
      github-environment: verigate-dev
      application-name: verigate
    permissions:
      id-token: write
      contents: read
      packages: write
    secrets: inherit

  dev-smoke-test:
    needs: [dev-deploy]
    uses: ./.github/workflows/_smoke-test.yml
    with:
      environment: dev
      github-environment: verigate-dev
    permissions:
      id-token: write
      contents: read
    secrets: inherit
