export const PROVIDER_OPTIONS: Record<string, string[]> = {
  ID: ["DHA"],
  IDENTITY: ["DHA"],
  DOCUMENT: ["VeriDoc"],
  AVS: ["Qlink", "ABSA"],
  CREDIT: ["TransUnion", "Experian", "XDS"],
  INCOME: ["Payroll Gateway"],
  TAX: ["SARS"],
  CIPC: ["CIPC"],
  DEEDS: ["Deeds Office"],
  EMPLOYMENT: ["Employer Direct"],
  QUALIFICATION: ["SAQA"],
  SANCTIONS: ["World-Check"],
  NEGATIVE_NEWS: ["Media24"],
  FRAUD_WATCHLIST: ["SAFPS"],
  WATCHLIST: ["World-Check"],
  FULL_VERIFICATION: ["VeriGate Composite"],
  BIOMETRIC: ["AWS Rekognition", "Smile ID"],
  LIVENESS: ["AWS Rekognition", "Smile ID"],
};
