package verigate.webbff.verification.model;

public enum VerificationType {
  VERIFICATION_OF_PERSONAL_DETAILS,
  VERIFICATION_OF_BANK_DETAILS,
  SANCTIONS_SCREENING,
  BANK_ACCOUNT_VERIFICATION,
  IDENTITY_VERIFICATION,
  COMPANY_VERIFICATION,
  PROPERTY_OWNERSHIP_VERIFICATION,
  EMPLOYMENT_VERIFICATION,
  NEGATIVE_NEWS_SCREENING,
  FRAUD_WATCHLIST_SCREENING,
  DOCUMENT_VERIFICATION,
  QUALIFICATION_VERIFICATION,
  CREDIT_CHECK,
  TAX_COMPLIANCE_VERIFICATION,
  INCOME_VERIFICATION,
  FULL_VERIFICATION,
  WATCHLIST_SCREENING,
  BIOMETRIC_VERIFICATION,
  LIVENESS_CHECK
}
