name: Release | VeriGate Develop

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "verigate-command-gateway/**"
      - "verigate-partner/**"
      - "verigate-billing/**"
      - "verigate-shared-kernel/**"

jobs:
  install:
    uses: ./.github/workflows/_install.yml
    with:
      java-version: "21"
    permissions:
      contents: read
      packages: read
    secrets: inherit

  integration-test:
    needs: [install]
    uses: ./.github/workflows/_test-integration-e2e.yml
    with:
      java-version: "21"
    permissions:
      contents: read
      packages: read
    secrets: inherit

  sandbox-terraform:
    needs: [install, integration-test]
    uses: ./.github/workflows/_release-terraform.yml
    concurrency: verigate-sandbox-terraform
    with:
      environment: sandbox
      github-environment: verigate-sandbox
      application-name: verigate
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  sandbox-sam:
    needs: [sandbox-terraform]
    uses: ./.github/workflows/_release-sam.yml
    concurrency: verigate-sandbox-sam
    with:
      environment: sandbox
      github-environment: verigate-sandbox
      application-name: verigate
      java-version: "21"
    permissions:
      id-token: write
      contents: read
      packages: read
    secrets: inherit

  sandbox-smoke-test:
    needs: [sandbox-sam]
    uses: ./.github/workflows/_smoke-test.yml
    with:
      environment: sandbox
      github-environment: verigate-sandbox
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  development-terraform:
    needs: [sandbox-smoke-test]
    uses: ./.github/workflows/_release-terraform.yml
    concurrency: verigate-development-terraform
    with:
      environment: development
      github-environment: verigate-development
      application-name: verigate
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  development-sam:
    needs: [development-terraform]
    uses: ./.github/workflows/_release-sam.yml
    concurrency: verigate-development-sam
    with:
      environment: development
      github-environment: verigate-development
      application-name: verigate
      java-version: "21"
    permissions:
      id-token: write
      contents: read
      packages: read
    secrets: inherit

  development-smoke-test:
    needs: [development-sam]
    uses: ./.github/workflows/_smoke-test.yml
    with:
      environment: development
      github-environment: verigate-development
    permissions:
      id-token: write
      contents: read
    secrets: inherit
