name: Release | VeriGate Develop

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "verigate-command-gateway/**"
      - "verigate-partner/**"
      - "verigate-billing/**"
      - "verigate-risk-engine/**"
      - "verigate-shared-kernel/**"

concurrency:
  group: verigate-dev
  cancel-in-progress: true

jobs:
  install:
    uses: ./.github/workflows/_install.yml
    with:
      java-version: "21"
    permissions:
      contents: read
      packages: read
    secrets: inherit

  integration-test:
    needs: [install]
    uses: ./.github/workflows/_test-integration-e2e.yml
    with:
      java-version: "21"
    permissions:
      contents: read
      packages: read
    secrets: inherit

  dev-terraform:
    needs: [install, integration-test]
    uses: ./.github/workflows/_release-terraform.yml
    concurrency: verigate-dev-terraform
    with:
      environment: dev
      github-environment: verigate-dev
      application-name: verigate
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  dev-sam:
    needs: [dev-terraform]
    uses: ./.github/workflows/_release-sam.yml
    concurrency: verigate-dev-sam
    with:
      environment: dev
      github-environment: verigate-dev
      application-name: verigate
      java-version: "21"
    permissions:
      id-token: write
      contents: read
      packages: read
    secrets: inherit

  dev-smoke-test:
    needs: [dev-sam]
    uses: ./.github/workflows/_smoke-test.yml
    with:
      environment: dev
      github-environment: verigate-dev
    permissions:
      id-token: write
      contents: read
    secrets: inherit
