name: Release | VeriGate Production

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

concurrency:
  group: verigate-prod
  cancel-in-progress: false

jobs:
  install:
    uses: ./.github/workflows/_install.yml
    with:
      java-version: "21"
    permissions:
      contents: read
      packages: read
    secrets: inherit

  prod-terraform:
    needs: [install]
    uses: ./.github/workflows/_release-terraform.yml
    concurrency: verigate-prod-terraform
    with:
      environment: prod
      github-environment: verigate-prod
      application-name: verigate
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  prod-sam:
    needs: [prod-terraform]
    uses: ./.github/workflows/_release-sam.yml
    concurrency: verigate-prod-sam
    with:
      environment: prod
      github-environment: verigate-prod
      application-name: verigate
      java-version: "21"
    permissions:
      id-token: write
      contents: read
      packages: read
    secrets: inherit

  prod-smoke-test:
    needs: [prod-sam]
    uses: ./.github/workflows/_smoke-test.yml
    with:
      environment: prod
      github-environment: verigate-prod
    permissions:
      id-token: write
      contents: read
    secrets: inherit
