name: Release | VeriGate Production

on:
  workflow_dispatch:
  push:
    branches:
      - "verigate-release"
      - "verigate-release-hotfix"

jobs:
  install:
    uses: ./.github/workflows/_install.yml
    with:
      java-version: "21"
    permissions:
      contents: read
      packages: read
    secrets: inherit

  preproduction-terraform:
    needs: [install]
    uses: ./.github/workflows/_release-terraform.yml
    concurrency: verigate-preproduction-terraform
    with:
      environment: preproduction
      github-environment: verigate-preproduction
      application-name: verigate
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  preproduction-sam:
    needs: [preproduction-terraform]
    uses: ./.github/workflows/_release-sam.yml
    concurrency: verigate-preproduction-sam
    with:
      environment: preproduction
      github-environment: verigate-preproduction
      application-name: verigate
      java-version: "21"
    permissions:
      id-token: write
      contents: read
      packages: read
    secrets: inherit

  preproduction-smoke-test:
    needs: [preproduction-sam]
    uses: ./.github/workflows/_smoke-test.yml
    with:
      environment: preproduction
      github-environment: verigate-preproduction
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  production-terraform:
    needs: [preproduction-smoke-test]
    uses: ./.github/workflows/_release-terraform.yml
    concurrency: verigate-production-terraform
    with:
      environment: production
      github-environment: verigate-production
      application-name: verigate
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  production-sam:
    needs: [production-terraform]
    uses: ./.github/workflows/_release-sam.yml
    concurrency: verigate-production-sam
    with:
      environment: production
      github-environment: verigate-production
      application-name: verigate
      java-version: "21"
    permissions:
      id-token: write
      contents: read
      packages: read
    secrets: inherit

  production-smoke-test:
    needs: [production-sam]
    uses: ./.github/workflows/_smoke-test.yml
    with:
      environment: production
      github-environment: verigate-production
    permissions:
      id-token: write
      contents: read
    secrets: inherit
